CREATE TABLE Manufacturer (
    manufacturer_id int NOT NULL,
    name varchar(50),
    PRIMARY KEY (manufacturer_id)
);

CREATE TABLE Product (
    product_id int NOT NULL,
    type varchar(15),
    name varchar(50),
    price numeric(7, 2),
    manufacturer_id int,
    PRIMARY KEY (product_id),
    FOREIGN KEY (manufacturer_id) REFERENCES Manufacturer
);

CREATE TABLE Sale (
    sale_id int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    time timestamp,
    product_id int NOT NULL,
    store_id int, 
    customer_id int,
    PRIMARY KEY (sale_id),
    FOREIGN KEY (product_id) REFERENCES Product,
    FOREIGN KEY (store_id) REFERENCES Store,
    FOREIGN KEY (customer_id) REFERENCES Customer
);

CREATE TABLE Online_Sales (
    sale_id int NOT NULL,
    tracking_number int NOT NULL,
    status varchar(10),
    FOREIGN KEY (sale_id) REFERENCES Sale
);

CREATE TABLE Store (
    store_id int NOT NULL,
    street varchar(80),
    city varchar(20),
    state varchar(20),
    zip_code int,
    region varchar(15),
    PRIMARY KEY (store_id)
);

CREATE TABLE Customer (
    customer_id int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name varchar(20),
    last_name varchar(20),
    street varchar(80),
    city varchar(20),
    state varchar(20),
    zip_code int,
    email varchar(40) NOT NULL, -- email is used to log in
    card_num NUMBER(19),
    PRIMARY KEY (customer_id),
    FOREIGN KEY (card_num) REFERENCES Card,
    UNIQUE (email)
);

CREATE TABLE Card (
    card_num NUMBER(19),
    cvv smallint,
    card_zip int,
    PRIMARY KEY (card_num)
);

CREATE TABLE Reorder (
    manufacturer_id int NOT NULL,
    store_id int NOT NULL,
    product_id int NOT NULL,
    filled bit,
    FOREIGN KEY (manufacturer_id) REFERENCES Manufacturer,
    FOREIGN KEY (store_id) REFERENCES Store,
    FOREIGN KEY (product_id) REFERENCES Product
);

CREATE TABLE Contract (
    customer_id int NOT NULL,
    manufacturer_id int NOT NULL,
    balance numeric(9, 2),
    FOREIGN KEY (customer_id) REFERENCES Customer,
    FOREIGN KEY (manufacturer_id) REFERENCES Manufacturer
);

CREATE TABLE Inventory (
    store_id int NOT NULL,
    product_id int NOT NULL,
    quantity int,
    FOREIGN KEY (store_id) REFERENCES Store,
    FOREIGN KEY (product_id) REFERENCES Product
);

CREATE TABLE Package (
    package_id int NOT NULL,
    child_id int NOT NULL,
    FOREIGN KEY (package_id) REFERENCES Product(product_id),
    FOREIGN KEY (child_id) REFERENCES Product(product_id)
);